--- === BuildBot.spoon ===
---
--- SC2 build order overlay
---
---



-- local logger  = require("hs.logger")

local obj = {}
obj.__index = obj

-- Metadata
obj.name = "BuildBot"
obj.version = "1.0"
obj.author = "andy williams <andy@nonissue.org>"
obj.homepage = "https://github.com/nonissue"
obj.license = "MIT - https://opensource.org/licenses/MIT"

-- local metadataKeys = {} ; for k, v in require("hs.fnutils").sortByKeys(obj) do table.insert(metadataKeys, k) end

-- local function script_path()
--     local str = debug.getinfo(2, "S").source:sub(2)
--     return str:match("(.*/)")
-- end

-- obj.spoonPath = script_path()

-- for timers when we add other queries so they don't get collected


-- Internal variables
obj.logger = hs.logger.new("BuildBot")
obj.overlayCanvas = nil
obj.hotkeyShow = nil

obj.defaultHotkeys = {
    showBuildBot = {{"ctrl", "cmd", "alt"}, "L"}
}

-- Add this to the object
obj.opacityLevels = {0.2, 0.4, 0.6, 0.8, 1.0}
obj.opacityIndex = 3 -- default to 0.6

-- Call this after the canvas is created
function obj:setOpacity(alpha)
    self.overlayCanvas[1].fillColor.alpha = alpha
end

function obj:bindHotkeys(keys)
    local hotkeys = keys or obj.defaultHotkeys

    hs.hotkey.bindSpec(
        hotkeys["showBuildBot"],
        function()
            self:toggle()
        end
    )
end

-- Default configuration

obj.textSize = 12
obj.buildOrderText = [[
Starcraft 2 Build Order

14 - Supply Depot
16 - Barracks
16 - Refinery
19 - Orbital Command
20 - Command Center
21 - Supply Depot
22 - Refinery #2
44 - associated
99 -
]]

function obj:init()
    local screenFrame = hs.screen.mainScreen():frame()
    local canvasWidth = screenFrame.w * 0.15
    local canvasHeight = screenFrame.h * 0.30

    self.overlayCanvas = hs.canvas.new({
        x = screenFrame.w - canvasWidth - 50,
        y = screenFrame.h * 0.2,
        w = canvasWidth,
        h = canvasHeight,

    })

    -- Background
    self.overlayCanvas:appendElements({
        type = "rectangle",
        action = "strokeAndFill",
        roundedRectRadii = {xRadius = 2, yRadius = 2},
        fillColor = {white = 0.1, alpha = self.opacityLevels[self.opacityIndex]},
        strokeWidth = 0,
        strokeColor = {white = 0.5, alpha = 0.5},
        trackMouseDown = true,
        shadow = { blurRadius = 0.0, color = { blue = 0, alpha = 1/3 }, offset = { h = -5.0, w = 5.0 } },
        withShadow = false
    })

    -- Text
    self.overlayCanvas:appendElements({
        type = "text",
        text = self.buildOrderText,
        textColor = {white = 1, alpha = 0.99},
        -- textColor = {blue = 1, alpha = self.opacityLevels[self.opacityIndex]},
        textSize = self.textSize,
        textAlignment = "left",
        textFont = "FiraCode-Retina",
        frame = {x = "5%", y = "5%", w = "100%", h = "100%"}
    })

    self.overlayCanvas:level(hs.canvas.windowLevels.floating)
    self.overlayCanvas:clickActivating(false)
    self.overlayCanvas:canvasMouseEvents(true, false, false, false)
    self.overlayCanvas:mouseCallback(function(_, _, _, _, button)
        if button then
        -- if button == 0 then -- Left click
            self.opacityIndex = (self.opacityIndex % #self.opacityLevels) + 1
            local newAlpha = self.opacityLevels[self.opacityIndex]
            self:setOpacity(newAlpha)
        end
    end)

    -- self.toggle(self)

    return self
end

function obj:toggle()
    if self.overlayCanvas:isShowing() then
        self.overlayCanvas:hide()
    else
        self.overlayCanvas:show()
    end
end

obj.start = function(self)
    self:init()
    -- in case called as function
    -- if self ~= obj then self = obj end
    return self
end

--- MenuOfFiles:stop() -> self
--- Method
--- Stops the processing and/or removes the displays generated by the MenuOfFiles spoon
---
--- Parameters:
---  * None
---
--- Returns:
---  * the MenuOfFiles spoon object
obj.stop = function(self)
    -- in case called as function
    if self ~= obj then self = obj end

    if self.overlayCanvas then
        self.overlayCanvas:delete()
        self.overlayCanvas = nil
    end
    if self.hotkey then
        self.hotkey:delete()
        self.hotkey = nil
    end

    return self
end

return obj
